import localFont from "next/font/local";
import "./globals.css";
import CustomSideBar from "@/components/level_1/CustomSideBar";
import LoginForm from "@/components/level_2/LoginForm";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <div>
            <CustomSideBar />
          </div>
          <LoginForm/>
          <div className="w-[100%] h-[100%]">{children}</div>
        </div>
      </body>
    </html>
  );
}
