# Generated by Django 5.1.4 on 2024-12-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='business_name',
            new_name='name',
        ),
    ]
